from __future__ import annotations

from typing import Any

# GX-D0: intentionally small grammar set. These are structural programs,
# not static pose images. Public naming/UX is deliberately not stable.
GROUP_TEMPLATES: dict[str, dict[str, Any]] = {
    "side_by_side": {
        "label": "Side-by-Side",
        "people_min": 2,
        "people_max": 4,
        "formation": "line",
        "depth_layers": 1,
        "contact_density": "low",
        "symmetry": "loose",
        "risk": "low",
        "slot_roles": ["anchor", "support", "optional", "optional"],
    },
    "v_inward_pair": {
        "label": "V / Inward Pair",
        "people_min": 2,
        "people_max": 3,
        "formation": "v",
        "depth_layers": 1,
        "contact_density": "low",
        "symmetry": "moderate",
        "risk": "low",
        "slot_roles": ["anchor", "support", "optional"],
    },
    "triangle": {
        "label": "Triangle",
        "people_min": 3,
        "people_max": 5,
        "formation": "triangle",
        "depth_layers": 2,
        "contact_density": "medium",
        "symmetry": "loose",
        "risk": "low",
        "slot_roles": ["anchor", "support", "support", "optional", "optional"],
    },
    "tight_cluster": {
        "label": "Tight Cluster",
        "people_min": 3,
        "people_max": 6,
        "formation": "cluster",
        "depth_layers": 2,
        "contact_density": "high",
        "symmetry": "low",
        "risk": "medium",
        "slot_roles": ["anchor", "support", "support", "optional", "optional", "optional"],
    },
    "center_wings": {
        "label": "Center + Wings",
        "people_min": 3,
        "people_max": 6,
        "formation": "center_wings",
        "depth_layers": 2,
        "contact_density": "medium",
        "symmetry": "moderate",
        "risk": "low",
        "slot_roles": ["anchor", "support", "support", "optional", "optional", "optional"],
    },
    "layered_editorial": {
        "label": "Layered Editorial",
        "people_min": 3,
        "people_max": 6,
        "formation": "layered_cluster",
        "depth_layers": 3,
        "contact_density": "low",
        "symmetry": "low",
        "risk": "high",
        "slot_roles": ["anchor", "support", "support", "optional", "optional", "optional"],
    },
}
