from __future__ import annotations
from typing import Any

def build_pose_target(analysis: dict[str, Any], plan: dict[str, Any], presets_by_id: dict[str, dict[str, Any]]) -> dict[str, Any]:
    if plan.get("selection_status") != "selected": return {"schema_version":"pose_target.v1","target_status":"preserve_original","selected_preset":None,"pose_target":{}}
    mechanics={}
    for component in plan["components"]:
        preset=presets_by_id[component["preset_id"]]; weight=float(component["weight"])
        for name,rule in preset.get("mechanics",{}).items():
            candidate=dict(rule)
            if isinstance(candidate.get("strength"),(int,float)): candidate["strength"]=round(float(candidate["strength"])*weight,4)
            existing=mechanics.get(name)
            if existing is None or (isinstance(candidate.get("strength"),(int,float)) and isinstance(existing.get("strength"),(int,float)) and candidate["strength"]>existing["strength"]): mechanics[name]=candidate
    primary=plan["components"][0]["preset_id"]
    return {"schema_version":"pose_target.v1","source_analysis_version":analysis["schema_version"],"target_status":"ready","selected_preset":{"preset_id":primary,"label":plan.get("label",primary),"intensity":"natural","selection_score":plan["ranked_candidates"][0]["score"]},"preservation":{item:"strict" for item in analysis.get("edit_plan",{}).get("preserve",[])},"pose_target":mechanics,"forbidden_changes":analysis.get("edit_plan",{}).get("avoid",[]),"edit_budget":{"maximum_pose_change":"moderate","background_reconstruction_allowance":"minimal","clothing_reconstruction_allowance":"minimal","limb_reconstruction_allowance":"low"},"fallback":{"if_target_not_feasible":"reduce_intensity","fallback_intensity":"subtle","if_still_not_feasible":"preserve_original_pose"}}

def build_generation_spec(target: dict[str, Any]) -> dict[str, Any]:
    preset=target.get("selected_preset")
    if target.get("target_status")!="ready" or not preset: raise ValueError("Pose target is not ready for generation")
    mechanics=[{"mechanic":name,"action":rule.get("action","adjust"),**({"strength":rule["strength"]} if "strength" in rule else {})} for name,rule in target.get("pose_target",{}).items()]
    return {"schema_version":"generation_spec.v1","source":{"image_id":"input_001","role":"authoritative_source","required":True},"task":{"type":"pose_correction","mode":"image_edit","output_count":1,"variation_policy":"controlled"},"selected_preset":{"preset_id":preset["preset_id"],"intensity":preset["intensity"]},"pose_target_ref":{"schema_version":"pose_target.v1","target_id":"target_001"},"preservation_hierarchy":list(target.get("preservation",{}).keys()),"transform":{"summary":f"Apply the minimum necessary correction for {preset['label']}.","mechanics":mechanics},"protected_regions":[{"region":"face","policy":"strict_preserve"},{"region":"hair","policy":"strict_preserve"},{"region":"hands","policy":"preserve_function_and_appearance"},{"region":"clothing","policy":"preserve_design_color_pattern_and_fit"},{"region":"accessories","policy":"strict_preserve"}],"mutable_regions":[],"scene_constraints":{"background":"preserve","lighting":"preserve","shadows":"preserve_and_reconcile","ground_contact":"strict","support_object_contact":"preserve","occlusion_order":"preserve","camera_position":"preserve","camera_height":"preserve","lens_character":"preserve","crop":"preserve"},"negative_constraints":list(target.get("forbidden_changes",[])),"edit_budget":target["edit_budget"],"regional_guidance":{"mask_strategy":"auto_if_supported","preferred_edit_region":"subject_body_excluding_face_when_possible","protect_face":True,"protect_background":True},"control_hints":{"pose_control":{"preferred":True,"required":False},"identity_reference":{"preferred":True,"required":False},"masking":{"preferred":True,"required":False},"seed_control":{"preferred":False,"required":False}},"output_requirements":{"preserve_resolution":True,"preserve_aspect_ratio":True,"minimum_quality":"production","return_metadata":True},"variation_plan":[{"variant_id":"natural","intensity_multiplier":1.0}],"retry_policy":{"max_attempts":2,"on_identity_drift":"reduce_edit_strength","on_background_drift":"tighten_preservation","on_anatomy_failure":"retry_with_stricter_pose_constraints","on_hand_failure":"preserve_original_hand_geometry","on_pose_failure":"fallback_to_lower_intensity"},"review_requirements":{"must_check":["identity_retention","pose_target_adherence","anatomical_plausibility","hand_quality","clothing_retention","background_retention","lighting_consistency","ground_contact"]}}
